# Generated by Django 4.2.4 on 2023-08-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='this is the deafult bio'),
        ),
    ]
